"""Lecture figures for chapter 8 (graphs.html), stored in assets/figures/ch8/."""
from html import escape

# fid: (file, display width, natural width, natural height, alt, caption)
_SPECS = {
    'digraph': ('digraph.png', 340, 438, 410,
                '六個頂點 V0 到 V5 的有向加權圖，共九條帶箭頭的邊，例如 V0→V1 權重 5、V5→V2 權重 1。',
                '一張簡單的有向加權圖。每條邊只能沿箭頭方向走，邊上的數字是權重。V3→V4→V0→V1 是一條路徑；V5→V2→V3→V5 繞回起點，是一個循環。'),
    'adjMat': ('adjMat.png', 340, 380, 380,
               '6×6 的表格，列與欄都標 V0 到 V5，只有九格填了數字，例如 V0 列 V1 欄是 5。',
               '上圖的相鄰矩陣。第 v 列第 w 欄的數字是邊 (v, w) 的權重，空白代表沒有邊。36 格裡只有 9 格有值，大部分空間都浪費掉了，這就是「稀疏」。'),
    'adjlist': ('adjlist.png', 760, 2640, 1200,
                'Graph 物件的 vertices map 有六個 key "V0" 到 "V5"，每個 key 指向一個 Vertex 物件，物件裡的 neighbors 記著鄰居與權重，例如 "V0" 的 neighbors 是 {"V1", 5}、{"V5", 2}。',
                '同一張圖的相鄰串列（本課程用 map 實作）。Graph 的 vertices 把 key 對應到 Vertex 物件；每個 Vertex 的 neighbors 只記實際存在的邊：鄰居的 key 對應到權重。沒有邊的組合完全不佔空間。'),
    'wordgraph': ('wordgraph.png', 600, 955, 419,
                  '單字圖：fool、pool、cool、foil、foul、poll、pole、pope、pall、pale、fall、fail、sale、page、sage 等頂點，只差一個字母的單字之間有邊；fool 與 sage 加框。',
                  'Word ladder 的圖：每個單字是一個頂點，兩個單字只差一個字母時連一條無向邊。從 fool 到 sage 的任何一條路徑，都是這個謎題的一個解。'),
    'wordbuckets': ('wordbuckets.png', 340, 367, 215,
                    '四個 bucket 標籤 _OPE、P_PE、PO_E、POP_，箭頭下方列出落入各 bucket 的單字，例如 POP_ 裡有 POPE 與 POPS。',
                    'POPE 依序把每個位置換成底線，落入 _OPE、P_PE、PO_E、POP_ 四個 bucket。同一個 bucket 裡的單字彼此只差那一個位置的字母，所以兩兩之間都要連邊。'),
    'bfs1': ('bfs1.png', 320, 371, 278,
             'fool 為黑色根節點，下方四個灰色節點 pool、foil、foul、cool，距離都是 1；佇列裡依序是 pool、foil、foul、cool。',
             'BFS 從 fool 出發：fool 的四個鄰居都還是白色，各自塗成灰色、距離設為 1、previous 指向 fool，並排進佇列。fool 的鄰居檢查完，fool 變成黑色。'),
    'bfs2': ('bfs2.png', 320, 389, 409,
             'pool 變成黑色，下方新增灰色的 poll，距離 2；佇列變成 foil、foul、cool、poll。',
             '取出佇列最前面的 pool。它的鄰居 cool 已經是灰色，不再處理；只有 poll 是新發現的頂點，距離 2，排到佇列最後面。'),
    'bfs3': ('bfs3.png', 420, 1560, 1080,
             '第一層四個節點 pool、foil、foul、cool 都變黑；第二層有灰色的 poll 與 fail，距離 2；佇列裡依序是 poll、fail。',
             '第一層的四個頂點都處理完：foil 帶出 fail，foul 和 cool 沒有新鄰居。第二層目前有 poll 與 fail 兩個灰色頂點，它們就是佇列裡等著展開的兩個頂點。'),
    'bfsDone': ('bfsDone.png', 500, 1800, 1860,
                'BFS 樹：fool 為根，下方是距離 1 到 6 的 14 個單字，全部是黑色；fall 掛在 fail 下面，pale 掛在 pall 下面，sage 在最底下，距離 6；佇列為空。',
                'BFS 結束時的搜尋樹。每個節點下方是它與 fool 的距離，箭頭就是 previous 指標。從任何一個單字沿箭頭往上走到 fool，就是它最短的 word ladder；sage 需要 6 步。所有頂點都處理完，全部是黑色，佇列也空了。'),
    'knightmoves': ('knightmoves.png', 460, 540, 306,
                    '左邊是 5×5 棋盤，格子編號 0 到 24，騎士在 12 號格，八個可跳到的格子標上圓點；右邊是以 12 為中心、連到 1、3、5、9、15、19、21、23 的星狀圖。',
                    '把棋盤畫成圖：每一格是一個頂點，編號是「列 × 棋盤大小 + 行」。騎士在 12 號格時有八種合法走法，每種走法就是一條從 12 出發的邊。'),
    'bigknight': ('bigknight.png', 480, 975, 933,
                  '8×8 棋盤的完整騎士圖，64 個頂點編號 0 到 63，邊密密麻麻地交錯。',
                  '8×8 棋盤上所有合法走法構成的圖。靠近棋盤邊緣與角落的頂點連線比較少，中間的頂點最多有 8 條連線。'),
    'ktdfsa': ('ktdfsa.png', 300, 256, 119,
               '六個頂點 A 到 F 的有向圖，A 為灰色，其餘白色。',
               '第 1 步：從 A 出發，A 塗成灰色並放進 path。'),
    'ktdfsb': ('ktdfsb.png', 300, 256, 119,
               'A、B 為灰色，其餘白色。',
               '第 2 步：A 的鄰居依 key 的順序先試 B。'),
    'ktdfsc': ('ktdfsc.png', 300, 256, 119,
               'A、B、C 為灰色，D、E、F 為白色。',
               '第 3 步：B 先試 C。C 沒有任何白色鄰居，path 長度又還不到 6，這是死路。'),
    'ktdfse': ('ktdfse.png', 300, 1104, 510,
               'A、B、D 為灰色，C、E、F 為白色。',
               '回溯之後：C 的呼叫回傳 false，程式把 C 移出 path 並塗回白色；B 改試下一個鄰居 D。'),
    'ktdfsf': ('ktdfsf.png', 300, 1104, 510,
               'A、B、D、E 為灰色，C、F 為白色。',
               '從 D 走到 E。C 仍是白色，要到最後一步才會再走到它。'),
    'ktdfsg': ('ktdfsg.png', 300, 256, 119,
               '六個頂點全部為灰色。',
               '從 E 走到 F，再從 F 走到已經變回白色的 C。path 長度達到 6，最後一層回傳 true，一路傳回最上層：path 是 A, B, D, E, F, C。'),
    'moveCount': ('moveCount.png', 300, 290, 290,
                  '8×8 表格，每格寫著騎士從該格出發的合法走法數：角落 2，角落旁 3，邊上 4 或 6，中央 8。',
                  '8×8 棋盤上每一格的合法走法數。角落只有 2 種，靠角落的格子 3 種，中央 16 格各有 8 種。'),
    '8arrayTree': ('8arrayTree.png', 640, 996, 343,
                   '一棵搜尋樹：根節點有 8 個子節點，下一層的節點又各有數個子節點，越往下越多。',
                   '把搜尋過程畫成樹：根是起點，每個子節點是一種下一步走法。每一層的分支數在 2 到 8 之間，樹的節點數隨深度以指數成長。'),
    'gendfsa': ('gendfsa.png', 300, 256, 119, 'A 為灰色，標 1/，其餘白色。',
                'dfsVisit(A)：A 塗灰色，discovery 為 1。'),
    'gendfsb': ('gendfsb.png', 300, 256, 119, 'A、B 為灰色，B 標 2/。',
                '依 key 的順序先走 B，discovery 為 2。'),
    'gendfsc': ('gendfsc.png', 300, 256, 119, 'A、B、C 為灰色，C 標 3/。',
                'B 先走 C，discovery 為 3。C 沒有鄰居。'),
    'gendfsd': ('gendfsd.png', 300, 256, 119,
                'A、B 為灰色；C 為黑色，標 3/4；D、E、F 為白色。粗線是 A→B、B→C 兩條樹邊。',
                'C 沒有可走的鄰居，探索完畢：塗成黑色，closing 為 4。粗線是搜尋樹的邊。接著回到 B，繼續看 B 的下一個鄰居。'),
    'gendfse': ('gendfse.png', 300, 256, 119, 'D 變為灰色，標 5/。',
                '回到 B，走 D，discovery 為 5。'),
    'gendfsf': ('gendfsf.png', 300, 256, 119, 'E 變為灰色，標 6/。',
                'D 走 E，discovery 為 6。'),
    'gendfsg': ('gendfsg.png', 300, 256, 119, 'F 變為灰色，標 7/；E→B 為虛線。',
                'E 的鄰居 B 是灰色，不能走（虛線），改走 F，discovery 為 7。'),
    'gendfsh': ('gendfsh.png', 300, 256, 119, 'F 變為黑色，標 7/8；F→C 為虛線。',
                'F 的鄰居 C 已經是黑色，F 探索完畢，closing 為 8。'),
    'gendfsi': ('gendfsi.png', 300, 256, 119, 'E 變為黑色，標 6/9。',
                '回到 E，E 也探索完畢，closing 為 9。'),
    'gendfsj': ('gendfsj.png', 300, 256, 119, 'D 變為黑色，標 5/10。',
                '回到 D，closing 為 10。'),
    'gendfsk': ('gendfsk.png', 300, 256, 119, 'B 變為黑色，標 2/11。',
                '回到 B，B 的鄰居都看過了，closing 為 11。'),
    'gendfsl': ('gendfsl.png', 300, 256, 119,
                '六個頂點全部為黑色：A 1/12、B 2/11、C 3/4、D 5/10、E 6/9、F 7/8；粗線是樹邊，虛線是檢查過但沒走的邊。',
                'DFS 結束：每個頂點都標上「discovery/closing」。粗線構成深度優先樹；虛線是檢查時另一端已經不是白色的邊。每個子孫的時間區間都包在祖先的區間裡。'),
    'pancakes': ('pancakes.png', 400, 437, 350,
                 '煎鬆餅步驟的有向圖：3/4 cup milk、1 egg、1 Tbl Oil 指向 1 cup mix；1 cup mix 指向 pour 1/4 cup 與 heat syrup；heat griddle 指向 pour 1/4 cup；pour 1/4 cup→turn when bubbly→eat；heat syrup→eat。',
                 '煎鬆餅的步驟圖。邊 (v, w) 表示 v 必須在 w 之前完成，例如牛奶、蛋、油都要先加進鬆餅粉才能攪拌。圖中沒有循環，是一張 DAG。'),
    'pancakesDFS': ('pancakesDFS.png', 400, 437, 350,
                    '同一張圖，每個頂點都塗成黑色並標上兩個時間，例如 3/4 cup milk 1/12、heat griddle 13/14、1 Tbl Oil 17/18。',
                    '對鬆餅圖跑 dfs() 之後，每個步驟都有 discovery/closing 時間。這張圖從 3/4 cup milk 開始搜尋；起點順序不同，時間也會不同。'),
    'pancakesTS': ('pancakesTS.png', 760, 1173, 162,
                   '九個步驟排成一列：1 Tbl Oil、1 egg、heat griddle、3/4 cup milk、1 cup mix、heat syrup、pour 1/4 cup、turn when bubbly、eat，所有箭頭都由左指向右。',
                   '依 closing 時間由大到小排列的結果。原圖的每條邊都從左指向右，所以照這個順序做，每一步的前置步驟都已經完成。'),
    'scc1': ('scc1.png', 420, 548, 389,
             '九個頂點的有向圖，分成三個陰影區：A、B、D、E、G 一區，C 一區（C 有指向自己的邊），F、H、I 一區。',
             '一張有三個強連通元件的圖，以不同深淺的區域標出。同一區裡任兩個頂點都能互相到達；區與區之間只有單向的邊，例如可以從 B 到 C，但回不到 B。'),
    'scc2': ('scc2.png', 300, 353, 193,
             '三個大節點 ABDEG、C、FHI，ABDEG 指向 C，C 指向 FHI，C 有一條指向自己的邊。',
             '把每個強連通元件縮成一個頂點後的簡化圖，比較容易看出原圖的整體結構。'),
    'scc1a': ('scc1a.png', 420, 512, 362,
              '原圖上每個頂點標著 discovery/closing 時間，例如 A 1/18、B 2/17、C 3/10。',
              '步驟 1：對原圖 G 跑 dfs()，得到每個頂點的 closing 時間。A 的 closing 時間 18 最大。'),
    'scc1b': ('scc1b.png', 420, 512, 362,
              '轉置圖上每條邊方向相反，頂點時間為第二次 DFS 的結果，例如 A 1/10、F 13/18。',
              '步驟 3：在轉置圖 Gᵀ 上跑 dfs()，主迴圈依第一次的 closing 時間由大到小挑起點。'),
    'sccforest': ('sccforest.png', 360, 462, 393,
                  '三棵樹：A→E→G→D 加上 E→B 一棵；C 單獨一棵；F→I→H 一棵。',
                  '步驟 3 產生的深度優先森林。三棵樹 {A, E, G, D, B}、{C}、{F, I, H} 正好是三個強連通元件。'),
    'Internet': ('Internet.png', 487, 487, 160,
                 '左邊兩台伺服器接 Router B，右邊三台電腦接 Router A，兩台路由器之間是一朵標著 Internet 的雲。',
                 '網際網路通訊的概觀：瀏覽器送出的請求先經過區域網路，再由路由器送進網際網路，最後到達伺服器所在網路的路由器。'),
    'routeGraph': ('routeGraph.png', 400, 413, 233,
                   '六個頂點 u、v、w、x、y、z 的無向加權圖，例如 u–x 權重 1、x–y 權重 1、y–z 權重 1、w–z 權重 5。',
                   '路由器連線的加權圖。頂點是路由器，邊上的權重是傳輸成本。要找的是總權重最小的路徑，不是經過最少路由器的路徑。'),
    'dijkstraa': ('dijkstraa.png', 440, 1512, 1308,
                  'Dijkstra after u：u 的距離 0；v=2、x=1、w=5，藍色是 previous 邊；下方 PQ 為 (1,"x")、(2,"v")、(5,"w")。',
                  '處理完 u 之後：u 的三個鄰居第一次得到有限的距離，previous 都指向 u（藍線）。下方列出優先佇列裡的 pair，最左邊的會最先被取出。'),
    'dijkstrab': ('dijkstrab.png', 440, 1512, 1308,
                  'after x：w 由 5 降為 4，y=2；PQ 為 (2,"v")、(2,"y")、(4,"w")、(5,"w")。',
                  '處理 x：經過 x 到 w 只要 1 + 3 = 4，比 5 小，所以更新 w 並推入 (4, "w")；舊的 (5, "w") 留在佇列裡。y 第一次得到距離 2。'),
    'dijkstrac': ('dijkstrac.png', 440, 1512, 1308,
                  'after v：距離沒有變化；PQ 為 (2,"y")、(4,"w")、(5,"w")。',
                  '處理 v：經過 v 到鄰居都不會更短，什麼都不變。'),
    'dijkstrad': ('dijkstrad.png', 440, 1512, 1308,
                  'after y：w 降為 3、z=3；PQ 為 (3,"w")、(3,"z")、(4,"w")、(5,"w")。',
                  '處理 y：w 再降到 3，z 第一次得到距離 3，兩者的 previous 都改成 y。'),
    'dijkstrae': ('dijkstrae.png', 440, 1512, 1308,
                  'after w：距離不變；PQ 為 (3,"z")、(4,"w")、(5,"w")。',
                  '處理 w（距離 3 的那一筆）：沒有更短的路。'),
    'dijkstraf': ('dijkstraf.png', 440, 1512, 1308,
                  'after z：所有距離確定，u=0、v=2、x=1、y=2、w=3、z=3；PQ 剩 (4,"w")、(5,"w")，標註略過剩下的過期項目直到佇列為空。',
                  '處理完 z：每個頂點的距離都確定了，藍線是最短路徑樹。佇列裡還剩 (4, "w") 與 (5, "w")，它們的距離大於 w 目前的距離，是過期的項目，取出後直接略過。'),
    'Dij': ('Dij.png', 380, 1200, 1176,
            '七個頂點 A 到 G 的有向加權圖，其中 C→D 權重 -5、E→G 權重 -7 兩條邊以橘色標出。',
            '練習 1 的圖：兩條橘色的邊權重是負數（C→D 為 −5、E→G 為 −7），其餘權重都是正數。'),
    'bcast1': ('bcast1.png', 420, 503, 399,
               '廣播主機連到路由器 A；路由器 A 到 G 以加權邊相連；聽眾 1 接 D、聽眾 2 接 E、聽眾 3 接 C、聽眾 4 接 G。',
               '廣播問題：廣播主機接在路由器 A，四位聽眾分別接在 D、E、C、G。邊上的數字是路由器之間的傳輸成本。'),
    'mst1': ('mst1.png', 340, 377, 303,
             '路由器 A 到 G 的加權圖，實線為 A–B、B–C、B–D、D–E、E–F、F–G 六條邊，虛線為 A–C、B–E、C–F。',
             '廣播圖的最小生成樹（實線）。六條邊連接全部七個路由器、沒有循環，總權重 2 + 1 + 1 + 1 + 1 + 1 = 7。虛線的邊不在樹上。'),
    'prima': ('prima.png', 380, 1440, 1560,
              'Prim after A：A 的 k=0；B k=2、C k=3，其餘 k=∞；PQ 為 (2,"B")、(3,"C")。',
              '從 A 開始：A 進入樹，它的鄰居 B、C 得到 key（連到樹的那條邊的權重）2 與 3。B、C 這時還不算在樹裡，要等它們從佇列取出才算。'),
    'primb': ('primb.png', 380, 1440, 1560,
              'after B：A–B 為藍色樹邊；C 的 k 改為 1，D=1、E=4；PQ 為 (1,"C")、(1,"D")、(3,"C")、(4,"E")。',
              '取出 B，加入邊 A–B。經 B 連到 C 只要 1，比 3 便宜，C 的 key 改成 1；D、E 第一次得到 key。'),
    'primc': ('primc.png', 380, 1440, 1560,
              'after C：B–C 為樹邊；F 的 k=5。',
              '取出 C（key 1），加入邊 B–C；C 的鄰居 F 得到 key 5。'),
    'primd': ('primd.png', 380, 1440, 1560,
              'after D：B–D 為樹邊；E 的 k 由 4 改為 1。',
              '取出 D，加入邊 B–D。經 D 連到 E 只要 1，E 的 key 從 4 改成 1，previous 也改指向 D。'),
    'prime': ('prime.png', 380, 1440, 1560,
              'after E：D–E 為樹邊；F 的 k 由 5 改為 1。',
              '取出 E，加入邊 D–E；F 的 key 從 5 改成 1。'),
    'primf': ('primf.png', 380, 1440, 1560,
              'after F：E–F 為樹邊；G 的 k=1。',
              '取出 F，加入邊 E–F；G 得到 key 1。'),
    'primg': ('primg.png', 380, 1440, 1560,
              'after G：六條藍色樹邊 A–B、B–C、B–D、D–E、E–F、F–G；略過剩下的過期項目，MST total weight = 7。',
              'G 加入之後，七個頂點都在樹裡，藍線就是最小生成樹，總權重 7。佇列裡剩下的 (3, "C")、(4, "E")、(5, "F") 都是過期的項目，取出後略過。'),
    'primq': ('primq.png', 560, 1920, 1056,
              '七個頂點 A 到 G 的無向加權圖：A–B 1、A–F 8、A–G 2、B–C 7、F–E 9、G–C 5、G–E 3、E–D 4、D–C 6。',
              '練習 2 的圖：無向加權圖，七個頂點、九條邊。'),
}

FIGURES = {fid: {'file': f, 'width': w, 'height': round(w * nh / nw), 'alt': alt, 'caption': cap}
           for fid, (f, w, nw, nh, alt, cap) in _SPECS.items()}


def figure(fid, caption=None):
    spec = FIGURES[fid]
    alt = escape(spec['alt'], quote=True)
    cap = spec['caption'] if caption is None else caption
    return (f'<figure class="gr-figure" id="gr-figure-{fid}">'
            f'<div class="gr-figure-scroll" tabindex="0" role="region" aria-label="{alt}">'
            f'<img src="assets/figures/ch8/{spec["file"]}" alt="{alt}" '
            f'width="{spec["width"]}" height="{spec["height"]}" style="--figure-width:{spec["width"]}px" loading="lazy"></div>'
            f'<figcaption>{escape(cap, quote=False)}</figcaption></figure>')


def steps(summary, fids, intro=''):
    """A step-by-step figure sequence, collapsed."""
    body = (f'<p>{intro}</p>' if intro else '') + '<div class="gr-steps">' + ''.join(figure(f) for f in fids) + '</div>'
    return f'<details class="gr-detail"><summary>{summary}</summary><div class="gr-detail-body">{body}</div></details>'


STYLE = '''<style id="graphs-figures-style">
.gr-figure{margin:1rem 0 1.4rem;max-width:100%;}
.gr-figure-scroll{max-width:100%;overflow-x:auto;background:#fff;border:1px solid var(--card-border);border-radius:8px;padding:.4rem 0;}
.gr-figure img{display:block;height:auto;max-width:100%;width:var(--figure-width);margin:0 auto;}
#gr-figure-adjlist img,#gr-figure-pancakesTS img{min-width:620px;}
.gr-figure figcaption{margin-top:.65rem;font-size:.9rem;line-height:1.8;color:var(--ink);}
.gr-steps{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:.4rem 1rem;}
.gr-steps .gr-figure{margin:.4rem 0;}
</style>'''
